### ISSUE TITLE
Terms of service and Privacy policy links are broken

### ISSUE THREAD

**Issue by qmonnet** [ebpf-io/ebpf.io-website#219]
The two links “Terms of service” and “Privacy policy”, in the page's footer, are broken. Content should probably be added for each.

**Comment by lizrice** [comment]
Wonder if we had some terms and privacy policy for cilium.io prior to its donation to CNCF? That might be a good starting point

**Comment by xmulligan** [comment]
Do we need a terms of service or a privacy policy or could we just remove them?

**Comment by borkmann** [comment]
(Wrt 'broken' links, some also still point to https://github.com/cilium/ebpf.io location.)
