### ISSUE TITLE
Add links to branding page

### ISSUE THREAD

**Issue by xmulligan** [ebpf-io/ebpf.io-website#227]
It would be great if there was an easy way for people to find logos

**Comment by frozenprocess** [comment]
Member or project logos?

**Comment by xmulligan** [comment]
Projects logos. We are waiting for the eBPF Foundation website to add this

**Comment by frozenprocess** [comment]
It would be neat to have some sort of splash image that rotates randomly through the logos.

**Comment by borkmann** [comment]
(closing, resolved)
