### ISSUE TITLE
Menu bit hard to use on mobile

### ISSUE THREAD

**Issue by borkmann** [ebpf-io/ebpf.io-website#268]
When navigating the ebpf.io page from mobile phone, the menu is hard to use given it disappears when scrolling down (e.g. for conferences where I'm unable to click on lsf/mm/bpf ones).

**Comment by l-monninger** [comment]
Good first issue?

**Comment by l-monninger** [comment]
@xmulligan Sounds good! Not sure when I'll have time. But, happy to help if I can. I came across this while checking you guys out on mobile, found the GitHub issue already here.

**Comment by xmulligan** [comment]
fixed with #348 thanks to @frozenprocess
