### ISSUE TITLE
hBPF logo doesn't match logo on hBPF site

### ISSUE THREAD

**Issue by dthaler** [ebpf-io/ebpf.io-website#272]
### Page(s) Affected
https://ebpf.io/infrastructure shows the hBPF logo as being vertically oriented.

### What Needs To Be Fixed?
https://github.com/rprinz08/hBPF
https://www.min.at/prinz/?x=cat:131
etc show the logo as rotated.

### Suggested Improvement
The logo should match the project website.

**Comment by xmulligan** [comment]
It looks like the original PR was from @rprinz08 for the vertical version. Can you let us know which one you prefer?

https://github.com/ebpf-io/ebpf.io-website/pull/140/files

**Comment by rprinz08** [comment]
Thx for the info. The vertically oriented logo is used without text and the rotated with text. But as you suggested it makes sense to harmonize this and also use the rotated one without text. So I can provide rotated one with a pull request if that's OK.

**Comment by xmulligan** [comment]
@rprinz08 That would be great if you could make the PR!

**Comment by rprinz08** [comment]
Updated with https://github.com/ebpf-io/ebpf.io-website/pull/273

**Comment by xmulligan** [comment]
Thanks for the update @rprinz08 and thanks for reporting @dthaler !
