### ISSUE TITLE
Visual issue in Conferences dropdown

### ISSUE THREAD

**Issue by frozenprocess** [ebpf-io/ebpf.io-website#347]
### Page(s) Affected
Since this is part of the header, I would say all of them.

### What Needs To Be Fixed?
Don't know if you have noticed, but it seems like the Conferences menu is growing like a weed. It is almost impossible to click on the bottom conferences if you are using a mobile device.
### Suggested Improvement
> Suggestion 1

Make it scrollable.

> Suggestion 2

Remove/limit the number of conferences from the menu (maybe to two years), and add an earlier button to the bottom of the dropdown that redirects to a separate page with all the conferences.

**Comment by xmulligan** [comment]
Looks like Suggestion 1 was fixed in #368

**Comment by frozenprocess** [comment]
Yep, I can confirm it is fixed!
