### ISSUE TITLE
Improve fallback landing page for documents not found (404 errors).

### ISSUE THREAD

**Issue by qmonnet** [ebpf-io/ebpf.io-website#383]
### Summary

We could improve the fallback landing page when a page is not found.

### Motivation

Current page for 404s:

![image](https://user-images.githubusercontent.com/17001771/227899050-a0aa9af4-734e-4728-9a78-9f4a88a797c6.png)

This is probably here for historical reasons, but doesn't look great in my opinion. `the sadaaaaaness`??

### Unresolved Questions

- What to use instead?
  -> I suppose something nice and/or fun, possibly with a design of a bee looking for something?

**Comment by xmulligan** [comment]
completed with #393
