### ISSUE TITLE
Missing HTML anchors on https://ebpf.io/infrastructure/ and https://ebpf.io/applications/

### ISSUE THREAD

**Issue by qmonnet** [ebpf-io/ebpf.io-website#460]
### Page(s) Affected

- https://ebpf.io/applications/
- https://ebpf.io/infrastructure/

### What Needs To Be Fixed?

We have HTML anchors (for example: https://ebpf.io/applications/#cilium) for most projects on these two pages. However:

- Page sections (“Major Applications” etc.) don't have anchors
- On https://ebpf.io/infrastructure/, for eBPF libraries, neither language subsections nor individual projects have anchors.

### Suggested Improvement

Add missing anchor targets :)

**Comment by prosazhin** [comment]
@qmonnet or @xmulligan
Hello. We have added anchors for sections, but a question has arisen that requires your input. Could you please tell how you are going to get links containing anchors? Perhaps we need to create a 'Copy Link' button including the anchor next to each item's name in the list?

**Comment by qmonnet** [comment]
Hi and thanks for this work!

> Perhaps we need to create a 'Copy Link' button including the anchor next to each item's name in the list?

Like for the sections in https://ebpf.io/what-is-ebpf/? That would be great! That's a good point, indeed it won't be easy to find the links otherwise. Personally I've been using [a dedicated browser add-on](https://github.com/brettz9/jump-to-anchor/) or occasionally looking at the HTML code, but a button would definitely make life easier for readers who want to point to a specific project's description.
