### ISSUE TITLE
Require "Emerging" projects to be actively maintained

### ISSUE THREAD

**Issue by dthaler** [ebpf-io/ebpf.io-website#463]
### Summary
Currently being "actively maintained" is a requirement for Major projects but not Emerging projects.
Brendan Gregg provided feedback that suggests that projects that are no longer maintained shouldn't be listed as "Emerging".

### Motivation
How can a project be "Emerging" if it's not actively maintained, so something can "emerge"?

**Comment by xmulligan** [comment]
I think that makes sense too, do you want to open a PR for it?
