### ISSUE TITLE
[Infrastructure landscape] Add logos for libraries

### ISSUE THREAD

**Issue by qmonnet** [ebpf-io/ebpf.io-website#498]
Now that several eBPF libraries have logos, it would be nice to display them in the infrastructure landscape.

- [cilium/eBPF](https://github.com/cilium/ebpf)
  ![](https://raw.githubusercontent.com/cilium/ebpf/main/docs/ebpf/ebpf-go.png) 

- [libbpfgo](https://github.com/aquasecurity/libbpfgo)
  <img src="https://github.com/aquasecurity/libbpfgo/raw/main/docs/images/aqua-tux.png" width="200px" />

- [libbpf](https://github.com/libbpf/libbpf/)
  <img src="https://github.com/libbpf/libbpf/raw/master/assets/libbpf-logo-sparse.png" width="400px" />

- [Aya](https://github.com/aya-rs/aya)
  <img src="https://github.com/aya-rs/aya/raw/main/assets/logo.svg" />

This will probably require reorganising the library box a little.

**Comment by xmulligan** [comment]
closed with #528
