### ISSUE TITLE
Invite link to Slack channel

### ISSUE THREAD

**Issue by florianl** [ebpf-io/ebpf.io-website#621]
### What Needs To Be Fixed?

In the footer of the page, there is an icon that should link to the slack channel.
It links to https://ebpf.io/slack which redirects to https://cilium.herokuapp.com/.

### Suggested Improvement

https://ebpf.io/slack should redirect to https://slack.cilium.io/.

**Comment by qmonnet** [comment]
Thanks Florian! I think Lorenz also reported the same internally, this morning. Here's a PR that should address it: #622
