### ISSUE TITLE
Forced i18n page redirects when selecting "english"

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [ebpf-io/ebpf.io-website#654]
### Page(s) Affected
Most pages

### What Needs To Be Fixed?
When using the english page, the current client side page forcefully redirects to appropriate i18n.
This is an issue when people want to use the english pages while using other localizations.

### Suggested Improvement
Disable redirections, or create separate en-us localization that is a mirror of the base pages.

**Comment by xmulligan** [comment]
Thanks for the suggestion, we implemented it here https://github.com/ebpf-io/ebpf.io-website/pull/655
